const translations = {
    en: {
        "nav-home": "Home",
        "nav-features": "Features",
        "nav-download": "Download",
        "nav-setup": "Setup",
        "nav-docs": "Documentation",
        "nav-developers": "Developers",
        "nav-lang": "Language",

        "hero-title": "MameCloudRom (MCR)",
        "hero-subtitle": "Virtual File System for MAME ROM Management",
        "hero-tagline": "Solve the \"ROM Version Hell\" - Only download when you want to play",
        "btn-quick-setup": "Quick Setup",
        "btn-learn-more": "Learn More",

        "disclaimer-title": "⚠ Important Legal Notice",
        "disclaimer-text": "This project does NOT include or distribute ROMs. It is a client-side file system tool. All content sources, downloading activities, and their legality are determined solely by the user, who assumes full responsibility.",
        "disclaimer-policy-title": "LEGAL & DMCA POLICY",
        "disclaimer-policy-intro": "This repository is a technical research project for virtual file system (VFS) implementation.",
        "disclaimer-item-1": "<strong>No Copyrighted Content</strong>: This repo does NOT host or distribute any game ROMs, BIOS files, or proprietary binaries.",
        "disclaimer-item-2": "<strong>Client-Side Tool</strong>: MCR is a \"utility pipe\" that fetches data from user-provided endpoints. The developer does not provide or maintain any ROM libraries.",
        "disclaimer-item-3": "<strong>Open Source</strong>: This code is provided under the MIT License as open-source software for technical research and legal use purposes.",
        "disclaimer-item-4": "<strong>Official Releases</strong>: Download official releases from our <a href=\"https://github.com/anomixer/MameCloudRom/releases\" target=\"_blank\">GitHub Releases page</a>.",

        "footer-text": "MameCloudRom (MCR) v1.0 - Developed by anomixer + Antigravity",
        "footer-license": "Distributed under MIT License",

        // Docs
        "docs-title": "Technical Documentation",
        "docs-subtitle": "Deep dive into the technical aspects of MameCloudRom (MCR)",
        "docs-motivation-title": "Motivation",
        "docs-motivation-p1": "MAME updates almost monthly, and with each update, ROM filenames and contents can change. This creates a vicious cycle where players are forced to download tens of gigabytes of update packages just to keep their sets compatible with the latest version. There is nothing more frustrating than wanting to play a quick game like <code>pacman</code>, only to find it won't start due to a version mismatch in your ROM set.",
        "docs-motivation-p2": "Most players only frequently play a small handful of games. Some third-party archival sites maintain up-to-date MAME-to-ROM mappings. MCR was born from this frustration: <strong>\"The proxy only fetches the correct ROM when you actually want to play the game.\"</strong>",
        "docs-motivation-p3": "It's designed to solve the \"ROM Version Hell\" faced by 95% of players. Stop managing files and start playing. The primary objective of this project is to research and validate file system proxying and lazy-fetching mechanisms.",

        "how-title": "How MCR Works",
        "how-subtitle": "MameCloudRom acts as an intelligent intermediary. Here is the sequence of events:",
        "step-1-title": "Interception",
        "step-1-desc": "When MAME searches for a ROM in its <code>-rompath Z:\\</code>, it sends standard file requests to Windows.",
        "step-2-title": "WinFsp Hand-off",
        "step-2-desc": "WinFsp intercepts these requests and passes them to the user-mode MCR application.",
        "step-3-title": "Cache Check",
        "step-3-desc": "MCR checks your local cache directory.<br><strong>Cache Hit:</strong> Served from disk.<br><strong>Cache Miss:</strong> MCR proceeds to download.",
        "step-4-title": "On-the-Fly Download",
        "step-4-desc": "MCR constructs the URL and triggers <code>curl</code> to fetch the file.",
        "step-5-title": "Seamless Delivery",
        "step-5-desc": "Once completed, MAME continues to load the game as if the file had always been there.",

        "arch-title": "System Architecture",
        "comp-mame-title": "MAME Emulator",
        "comp-mame-desc": "Requests ROM files via virtual filesystem (default Z:\\).",
        "comp-winfsp-title": "WinFsp Layer",
        "comp-winfsp-desc": "Handles kernel-level filesystem operations and forwards requests.",
        "comp-mcr-title": "MCR Application",
        "comp-mcr-desc": "Core logic for lazy-loading (Cache or Download).",
        "comp-remote-title": "Remote Source",
        "comp-remote-desc": "Your configured external URL hosting the ROM files.",
        "comp-cache-title": "Local Cache",
        "comp-cache-desc": "Stores downloaded files to avoid repeated downloads.",

        "scope-title": "Supported Scope & Limitations",
        "supported-title": "Supported",
        "unsupported-title": "Unsupported",
        "scope-item-1": "Game ROMs (<code>.zip</code>, <code>.7z</code>) requested via <code>rompath</code>",
        "scope-item-2": "Various device/BIOS files requested via <code>rompath</code>",
        "scope-item-3": "Windows File Explorer browsing of the virtual filesystem",
        "scope-item-4": "MAME auditing without triggering downloads (optimized scanning)",
        "scope-limit-1": "<strong>Large CHD Files</strong>: Recommended to manage CHD files manually due to size.",
        "scope-limit-2": "<strong>Auxiliary Assets</strong>: Snaps, icons, samples are best managed manually.",
        "scope-limit-3": "<strong>File Deletion</strong>: Deleting files on <code>Z:\\</code> is ineffective. Delete from local Cache directory instead.",

        // Features
        "feat-title": "Key Features",
        "feat-subtitle": "Powerful capabilities for seamless MAME ROM management",
        "feat-1-title": "On-Demand Download",
        "feat-1-desc": "Files are only downloaded when accessed, saving local disk space.",
        "feat-2-title": "WinFsp Integration",
        "feat-2-desc": "High-performance virtual disk driver with optimized Stateless mode.",
        "feat-3-title": "Stateless Stability",
        "feat-3-desc": "Solved \"Too many links\" errors by enforcing stable metadata.",
        "feat-4-title": "Explorer Friendly",
        "feat-4-desc": "Fully compatible with Windows File Explorer (8-byte alignment fix).",
        "feat-5-title": "Scan Optimization",
        "feat-5-desc": "MAME auditing doesn't trigger downloads, making launch near-instant.",
        "feat-6-title": "Extreme Stability",
        "feat-6-desc": "Optimized handle protection logic ensuring 100% stability.",
        "feat-7-title": "Custom Prefixes",
        "feat-7-desc": "Supports -zp and -7p prefixes to adapt to any server structure.",
        "feat-8-title": "Detailed Downloader",
        "feat-8-desc": "Real-time progress bars via curl and file size display.",
        "feat-9-title": "Auto-Config",
        "feat-9-desc": "Easy setup via setup.bat and configuration via config.bat.",

        // Setup
        "setup-title": "Setup Guide",
        "setup-subtitle": "Learn how to install and configure MameCloudRom",
        "prereq-title": "Prerequisites",
        "setup-step-1-title": "1. Run setup.bat",
        "setup-step-1-desc": "First-time installation. (Use <code>config.bat</code> later for changes).",
        "setup-step-2-title": "2. Follow Prompts",
        "setup-step-2-desc": "Set your cache, drive letter, MAME path, and URL prefixes.",
        "setup-step-3-title": "3. Generated Files",
        "setup-step-3-desc": "The script creates <code>mcr.ini</code> and <code>mcr-run.bat</code>.",
        "setup-step-4-title": "4. Run mcr-run.bat",
        "setup-step-4-desc": "Starts the virtual drive and automatically launches MAME.",

        // Download
        "download-title": "Download MameCloudRom",
        "download-subtitle": "Get the latest version of MCR",
        "release-v10": "MCR v1.0 (2026-01-13)",
        "download-pkg-title": "MameCloudRom Package",
        "download-pkg-desc": "Complete package with executable, scripts, and configs.",
        "download-pkg-btn": "Download MameCloudRom.zip",
        "download-src-title": "Source Code",
        "download-src-desc": "For developers who want to build from source.",
        "download-src-btn": "Browse Source",
        "download-post-info": "After downloading, extract the .zip file to your preferred directory. Then follow the <a href='setup.html'>Setup Guide</a>.",
        "dev-subtitle": "Build from source and contribute to the project",
        "dev-build-title": "Build Instructions",
        "dev-step-1-title": "WinFsp Developer Components",
        "dev-step-1-desc": "Install WinFsp with \"Core\" and \"Developer\" components enabled.",
        "dev-step-2-title": "Visual Studio 2022",
        "dev-step-2-desc": "Open the project folder; CMake will auto-configure.",
        "dev-step-3-title": "Release Config",
        "dev-step-3-desc": "Select <code>Release</code> and \"Build All\".",
        "dev-step-4-title": "Build Script",
        "dev-step-4-desc": "Alternatively, run <code>build.bat</code> from the root directory."
    },
    zh_TW: {
        "nav-home": "首頁",
        "nav-features": "功能特色",
        "nav-download": "下載",
        "nav-setup": "設定指南",
        "nav-docs": "技術文檔",
        "nav-developers": "開發者",
        "nav-lang": "語言",

        "hero-title": "MameCloudRom (MCR)",
        "hero-subtitle": "專為 MAME ROM 管理設計的虛擬檔案系統",
        "hero-tagline": "解決「ROM 版本地獄」— 只有當你想玩時才即時下載",
        "btn-quick-setup": "快速設定",
        "btn-learn-more": "了解更多",

        "disclaimer-title": "⚠ 重要法律聲明",
        "disclaimer-text": "本專案「不包含」亦「不分發」任何 ROM 檔案。這是一個客戶端檔案系統技術工具，所有內容來源、下載行為及其合法性均由使用者自行決定並承擔全部責任。",
        "disclaimer-policy-title": "法律與 DMCA 政策聲明",
        "disclaimer-policy-intro": "本儲存庫是一個關於虛擬文件系統 (VFS) 實現的技術研究項目。",
        "disclaimer-item-1": "<strong>無版權內容</strong>：本倉庫不託管、不儲存、亦不分發任何遊戲 ROM、BIOS 文件或受版權保護的專有文件。",
        "disclaimer-item-2": "<strong>客戶端工具</strong>：MCR 僅作為一種「數據管道」技術工具，其功能是根據用戶提供的來源獲取數據。開發者不提供、亦不維護任何 ROM 資源庫。",
        "disclaimer-item-3": "<strong>開放原始碼</strong>：本專案代碼基於 MIT 授權條款發佈，作為開源軟體供技術研究與合法用途使用。",
        "disclaimer-item-4": "<strong>正式發布版本</strong>：從我們的 <a href=\"https://github.com/anomixer/MameCloudRom/releases\" target=\"_blank\">GitHub Releases 頁面</a> 下載。",

        "footer-text": "MameCloudRom (MCR) v1.0 - 開發者：anomixer + Antigravity",
        "footer-license": "按 MIT 授權條款分發",

        // Docs
        "docs-title": "技術文檔",
        "docs-subtitle": "深入探討 MameCloudRom (MCR) 的技術細節",
        "docs-motivation-title": "開發動機",
        "docs-motivation-p1": "MAME 幾乎每個月都會更新，且每次更新時 ROM 的檔名與內容都可能重新編排。這導致玩家每更新一次 MAME 版本，就得對應下載幾十 GB 的 ROM 合集更新。如果你想玩某款遊戲（例如 <code>pacman</code>），卻因為新版 MAME 對應不到舊版 ROM 而無法啟動，那是很令人沮喪的。",
        "docs-motivation-p2": "許多第三方存檔網站 (Archive sites) 會即時更新與最新 MAME 版本對應的 ROM。這就是開發 MCR 的初衷：<strong>「只有當你想玩某款遊戲時，代理程式才即時去抓取對應的 ROM」</strong>。",
        "docs-motivation-p3": "它設計用來解決 95% 玩家都會遇到的「ROM 版本地獄」，把時間留給遊戲，而不是研究檔案。本專案的設計目標在於研究與驗證檔案系統代理與延遲獲取機制。",

        "how-title": "工作原理",
        "how-subtitle": "MameCloudRom 充當智能中介。以下是啟動遊戲時的流程：",
        "step-1-title": "攔截請求",
        "step-1-desc": "當 MAME 嘗試從虛擬磁碟（如 <code>Z:\\</code>）讀取 ROM 時，會向 Windows 發送標準請求。",
        "step-2-title": "WinFsp 介入",
        "step-2-desc": "WinFsp 攔截請求並將其轉交給使用者模式的 MCR 應用程式。",
        "step-3-title": "快取檢查",
        "step-3-desc": "MCR 檢查本地快取目錄。<br><strong>快取命中：</strong>直接從磁碟讀取。<br><strong>快取未命中：</strong>MCR 進入下載流程。",
        "step-4-title": "即時下載",
        "step-4-desc": "MCR 構造正確 URL 並呼叫 <code>curl</code> 從遠端伺服器下載檔案。",
        "step-5-title": "無縫銜接",
        "step-5-desc": "下載完成後，MAME 隨即讀取到檔案並啟動遊戲。",

        "arch-title": "系統架構",
        "comp-mame-title": "MAME 模擬器",
        "comp-mame-desc": "透過虛擬檔案系統 (預設 Z:\\) 請求 ROM 檔案。",
        "comp-winfsp-title": "WinFsp 層",
        "comp-winfsp-desc": "處理核心級檔案系統操作並轉發請求。",
        "comp-mcr-title": "MCR 應用程式",
        "comp-mcr-desc": "延遲載入的核心邏輯（判斷快取或下載）。",
        "comp-remote-title": "遠端來源",
        "comp-remote-desc": "您設定的外部 ROM 檔案下載網址。",
        "comp-cache-title": "本地快取",
        "comp-cache-desc": "儲存已下載的檔案，避免重複下載。",

        "scope-title": "支援範圍與限制",
        "supported-title": "支援項目",
        "unsupported-title": "限制與不支援",
        "scope-item-1": "透過 <code>rompath</code> 請求的遊戲 ROM (<code>.zip</code>, <code>.7z</code>)",
        "scope-item-2": "透過 <code>rompath</code> 請求的各種裝置/BIOS 檔案",
        "scope-item-3": "支援 Windows 檔案總管完整瀏覽內容",
        "scope-item-4": "MAME 掃描 (Audit) 時不觸發下載，大幅提升啟動速度",
        "scope-limit-1": "<strong>大型 CHD 檔案</strong>：體積巨大，建議自行管理。",
        "scope-limit-2": "<strong>輔助資源</strong>：快照、圖示、取樣檔建議手動管理。",
        "scope-limit-3": "<strong>檔案刪除</strong>：在 <code>Z:\\</code> 執行刪除無效，請至快取目錄操作。",

        // Features
        "feat-title": "主要特色",
        "feat-subtitle": "強大功能，實現無縫的 MAME ROM 管理體驗",
        "feat-1-title": "即時下載",
        "feat-1-desc": "只有在開啟檔案時才會觸發下載，節省硬碟空間。",
        "feat-2-title": "WinFsp 整合",
        "feat-2-desc": "高效能虛擬磁碟驅動，具備優化的「無狀態」模式。",
        "feat-3-title": "無狀態穩定性",
        "feat-3-desc": "解決「Too many links」錯誤，確保中繼資料穩定。",
        "feat-4-title": "檔案總管相容",
        "feat-4-desc": "修正 8-byte 對齊問題，檔案總管瀏覽穩如泰山。",
        "feat-5-title": "掃描效能優化",
        "feat-5-desc": "自動區分 MAME 的「掃描」與「讀取」，啟動近乎即時。",
        "feat-6-title": "極致穩定技術",
        "feat-6-desc": "採用 v0.2 的句柄保護機制，解決高頻操作下的穩定性問題。",
        "feat-7-title": "自定義路徑字首",
        "feat-7-desc": "支援 -zp 與 -7p，適應任何遠端伺服器目錄結構。",
        "feat-8-title": "增強型下載資訊",
        "feat-8-desc": "支援 curl 進度條與顯示 ROM 檔案大小 (MB/KB)。",
        "feat-9-title": "全自動化配置",
        "feat-9-desc": "透過 setup.bat 與 config.bat 一鍵設定環境。",

        // Setup
        "setup-title": "設定指南",
        "setup-subtitle": "了解如何安裝並配置 MameCloudRom",
        "prereq-title": "系統需求與必備組件",
        "setup-step-1-title": "1. 執行 setup.bat",
        "setup-step-1-desc": "進行初次安裝。（日後變更設定請直接執行 <code>config.bat</code>）。",
        "setup-step-2-title": "2. 按照提示設定",
        "setup-step-2-desc": "設定快取目錄、磁碟代號、MAME 路徑與 URL 前綴。",
        "setup-step-3-title": "3. 自動產生檔案",
        "setup-step-3-desc": "腳本會自動建立 <code>mcr.ini</code> 與 <code>mcr-run.bat</code>。",
        "setup-step-4-title": "4. 執行 mcr-run.bat",
        "setup-step-4-desc": "啟動虛擬磁碟並同時自動開啟 MAME。",

        // Download
        "download-title": "下載 MameCloudRom",
        "download-subtitle": "取得 MCR 最新版本",
        "release-v10": "MCR v1.0 (2026-01-13)",
        "download-pkg-title": "MameCloudRom 完整套件",
        "download-pkg-desc": "包含執行檔、腳本與設定範例的壓縮包。",
        "download-pkg-btn": "下載 MameCloudRom.zip",
        "download-src-title": "原始碼",
        "download-src-desc": "適合想要自行編譯的開發者。",
        "download-src-btn": "瀏覽原始碼",
        "download-post-info": "下載後，請將 .zip 檔案解壓縮到您想要存放的目錄，接著按照<a href='setup.html'>設定指南</a>進行操作。",
        "dev-subtitle": "從原始碼編譯並為專案做出貢獻",
        "dev-build-title": "編譯指南",
        "dev-step-1-title": "WinFsp 開發者組件",
        "dev-step-1-desc": "安裝 WinFsp 時，請確保勾選了「Core」與「Developer」組件。",
        "dev-step-2-title": "Visual Studio 2022",
        "dev-step-2-desc": "直接開啟專案資料夾；CMake 會自動完成配置。",
        "dev-step-3-title": "Release 模式",
        "dev-step-3-desc": "選擇 <code>Release</code> 配置並點擊「全部建置」。",
        "dev-step-4-title": "編譯腳本",
        "dev-step-4-desc": "或者，您也可以直接執行根目錄下的 <code>build.bat</code>。"
    },
    zh_CN: {
        "nav-home": "首页",
        "nav-features": "功能特色",
        "nav-download": "下载",
        "nav-setup": "设置指南",
        "nav-docs": "技术文档",
        "nav-developers": "开发者",
        "nav-lang": "语言",

        "hero-title": "MameCloudRom (MCR)",
        "hero-subtitle": "专为 MAME ROM 管理设计的虚拟文件系统",
        "hero-tagline": "解决“ROM 版本地狱” — 只有当你想玩时才即时下载",
        "btn-quick-setup": "快速设置",
        "btn-learn-more": "了解更多",

        "disclaimer-title": "⚠ 重要法律声明",
        "disclaimer-text": "本项目「不包含」亦「不分发」任何 ROM 文件。这是一个客户端文件系统技术工具，所有内容来源、下载行为及其合法性均由用户自行决定并承担全部责任。",
        "disclaimer-policy-title": "法律与 DMCA 政策声明",
        "disclaimer-policy-intro": "本存储库是一个关于虚拟文件系统 (VFS) 实现的技术研究项目。",
        "disclaimer-item-1": "<strong>无版权内容</strong>：本仓库不托管、不存储、亦不分发任何游戏 ROM、BIOS 文件或受版权保护的专有文件。",
        "disclaimer-item-2": "<strong>客户端工具</strong>：MCR 仅作为一种“数据管道”技术工具，其功能是根据用户提供的来源获取数据。开发者不提供、亦不维护任何 ROM 资源库。",
        "disclaimer-item-3": "<strong>开放源代码</strong>：本项目代码基于 MIT 授权条款发布，作为开源软件供技术研究与合法用途使用。",
        "disclaimer-item-4": "<strong>正式发布版本</strong>：从我们的 <a href=\"https://github.com/anomixer/MameCloudRom/releases\" target=\"_blank\">GitHub Releases 页面</a> 下载。",

        "footer-text": "MameCloudRom (MCR) v1.0 - 开发者：anomixer + Antigravity",
        "footer-license": "按 MIT 授权条款分发",

        // Docs
        "docs-title": "技术文档",
        "docs-subtitle": "深入探讨 MameCloudRom (MCR) 的技术细节",
        "docs-motivation-title": "开发动机",
        "docs-motivation-p1": "MAME 几乎每个月都会更新，且每次更新时 ROM 的文件名与内容都可能重新编排。这导致玩家每更新一次 MAME 版本，就得对应下载几十 GB 的 ROM 合集更新。如果你想玩某款游戏（例如 <code>pacman</code>），却因为新版 MAME 对应不到旧版 ROM 而无法启动，那是一件非常令人沮丧的事情。",
        "docs-motivation-p2": "许多第三方存档网站 (Archive sites) 会即时更新与最新 MAME 版本对应的 ROM。这就是开发 MCR 的初衷：<strong>“只有当你想玩某款游戏时，代理程序才即时去抓取对应的 ROM”</strong>。",
        "docs-motivation-p3": "它设计用来解决 95% 玩家都会遇到的“ROM 版本地狱”，把时间留给游戏，而不是研究文件。本项目的设计目标在于研究与验证文件系统代理与延迟获取机制。",

        "how-title": "工作原理",
        "how-subtitle": "MameCloudRom 充当智能中介。以下是启动游戏时的流程：",
        "step-1-title": "拦截请求",
        "step-1-desc": "当 MAME 尝试从虚拟磁盘（如 <code>Z:\\</code>）读取 ROM 时，会向 Windows 发送标准请求。",
        "step-2-title": "WinFsp 介入",
        "step-2-desc": "WinFsp 拦截请求并将其转交给用户模式的 MCR 应用程序。",
        "step-3-title": "缓存检查",
        "step-3-desc": "MCR 检查本地缓存目录。<br><strong>缓存命中：</strong>直接从磁盘读取。<br><strong>缓存未命中：</strong>MCR 进入下载流程。",
        "step-4-title": "即时下载",
        "step-4-desc": "MCR 构造正确 URL 并调用 <code>curl</code> 从远程服务器下载文件。",
        "step-5-title": "无缝衔接",
        "step-5-desc": "下载完成后，MAME 随即读取到文件并启动游戏。",

        "arch-title": "系统架构",
        "comp-mame-title": "MAME 模拟器",
        "comp-mame-desc": "通过虚拟文件系统 (默认 Z:\\) 请求 ROM 文件。",
        "comp-winfsp-title": "WinFsp 层",
        "comp-winfsp-desc": "处理内核级文件系统操作并转发请求。",
        "comp-mcr-title": "MCR 应用程序",
        "comp-mcr-desc": "延迟加载的核心逻辑（判断缓存或下载）。",
        "comp-remote-title": "远程来源",
        "comp-remote-desc": "您设置的外部 ROM 文件下载网址。",
        "comp-cache-title": "本地缓存",
        "comp-cache-desc": "存储已下载的文件，避免重复下载。",

        "scope-title": "支持范围与限制",
        "supported-title": "支持项目",
        "unsupported-title": "限制与不支持",
        "scope-item-1": "通过 <code>rompath</code> 请求的游戏 ROM (<code>.zip</code>, <code>.7z</code>)",
        "scope-item-2": "通过 <code>rompath</code> 请求的各种设备/BIOS 文件",
        "scope-item-3": "支持 Windows 资源管理器完整浏览内容",
        "scope-item-4": "MAME 扫描 (Audit) 时不触发下载，大幅提升启动速度",
        "scope-limit-1": "<strong>大型 CHD 文件</strong>：体积巨大，建议自行管理。",
        "scope-limit-2": "<strong>辅助资源</strong>：快照、图标、采样文件建议手动管理。",
        "scope-limit-3": "<strong>文件删除</strong>：在 <code>Z:\\</code> 执行删除无效，请至缓存目录操作。",

        // Features
        "feat-title": "主要特色",
        "feat-subtitle": "强大功能，实现无缝的 MAME ROM 管理体验",
        "feat-1-title": "即时下载",
        "feat-1-desc": "只有在打开文件时才会触发下载，节省硬盘空间。",
        "feat-2-title": "WinFsp 整合",
        "feat-2-desc": "高性能虚拟磁盘驱动，具备优化的“无状态”模式。",
        "feat-3-title": "无状态稳定性",
        "feat-3-desc": "解决“Too many links”错误，确保元数据稳定。",
        "feat-4-title": "资源管理器兼容",
        "feat-4-desc": "修正 8-byte 对齐问题，资源管理器浏览稳如泰山。",
        "feat-5-title": "扫描性能优化",
        "feat-5-desc": "自动区分 MAME 的“扫描”与“读取”，启动近乎即时。",
        "feat-6-title": "极致稳定技术",
        "feat-6-desc": "采用 v0.2 的句柄保护机制，解决高频操作下的稳定性问题。",
        "feat-7-title": "自定义路径前缀",
        "feat-7-desc": "支持 -zp 与 -7p，适应任何远程服务器目录结构。",
        "feat-8-title": "增强型下载信息",
        "feat-8-desc": "支持 curl 进度条与显示 ROM 文件大小 (MB/KB)。",
        "feat-9-title": "全自动化配置",
        "feat-9-desc": "通过 setup.bat 与 config.bat 一键设置环境。",

        // Setup
        "setup-title": "设置指南",
        "setup-subtitle": "了解如何安装并配置 MameCloudRom",
        "prereq-title": "系统需求与必备组件",
        "setup-step-1-title": "1. 运行 setup.bat",
        "setup-step-1-desc": "进行初次安装。（日后变更设置请直接运行 <code>config.bat</code>）。",
        "setup-step-2-title": "2. 按照提示设置",
        "setup-step-2-desc": "设置缓存目录、驱动器盘符、MAME 路径与 URL 前缀。",
        "setup-step-3-title": "3. 自动生成文件",
        "setup-step-3-desc": "脚本会自动建立 <code>mcr.ini</code> 与 <code>mcr-run.bat</code>。",
        "setup-step-4-title": "4. 运行 mcr-run.bat",
        "setup-step-4-desc": "启动虚拟磁盘并同时自动开启 MAME。",

        // Download
        "download-title": "下载 MameCloudRom",
        "download-subtitle": "取得 MCR 最新版本",
        "release-v10": "MCR v1.0 (2026-01-13)",
        "download-pkg-title": "MameCloudRom 完整套件",
        "download-pkg-desc": "包含执行文件、脚本与配置示例的压缩包。",
        "download-pkg-btn": "下载 MameCloudRom.zip",
        "download-src-title": "源代码",
        "download-src-desc": "适合想要自行编译的开发者。",
        "download-src-btn": "浏览源代码",
        "download-post-info": "下载后，请将 .zip 文件解压缩到您想要存放的目录，接着按照<a href='setup.html'>设置指南</a>进行操作。",
        "dev-subtitle": "从源代码编译並为项目做出贡献",
        "dev-build-title": "编译指南",
        "dev-step-1-title": "WinFsp 开发者组件",
        "dev-step-1-desc": "安装 WinFsp 时，请确保勾选了“Core”与“Developer”组件。",
        "dev-step-2-title": "Visual Studio 2022",
        "dev-step-2-desc": "直接打开项目文件夹；CMake 会自动完成配置。",
        "dev-step-3-title": "Release 模式",
        "dev-step-3-desc": "选择 <code>Release</code> 配置并点击“全部生成”。",
        "dev-step-4-title": "编译脚本",
        "dev-step-4-desc": "或者，您也可以直接运行根目录下的 <code>build.bat</code>。"
    }
};

// Current language
let currentLanguage = localStorage.getItem('mcr_language') || 'en';

// Change language function
function changeLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('mcr_language', lang);
    updatePageContent();
}

// Update page content based on selected language
function updatePageContent() {
    const t = translations[currentLanguage];

    // Update all elements with data-i18n attribute
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key]) {
            el.innerHTML = t[key];
        }
    });

    // Update active state in language dropdown if needed
    // (Optional: can add visual indicator for current language)
}

// Initialize on page load
document.addEventListener('DOMContentLoaded', updatePageContent);